# Generated by Django 5.2.17 on 2026-09-14 12:28

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=20)),
                ('idempotency_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.wallet')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0), ('balance__lte', Decimal('999999999999.99999999'))), name='wallet_balance_range'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', 'id'], name='ledger_wallet_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lte', Decimal('999999999999.99999999'))), name='ledger_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0), ('balance_before__lte', Decimal('999999999999.99999999'))), name='ledger_before_range'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0), ('balance_after__lte', Decimal('999999999999.99999999'))), name='ledger_after_range'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['credit', 'debit'])), name='ledger_known_type'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'credit'), _negated=True), ('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '+', models.F('amount'))), _connector='OR'), name='ledger_credit_arithmetic'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'debit'), _negated=True), ('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '-', models.F('amount'))), _connector='OR'), name='ledger_debit_arithmetic'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('wallet', 'idempotency_key'), name='ledger_wallet_key_unique'),
        ),
    ]
