# Generated by Django 5.2.17 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgerentry",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="ledger_wallet_id_idx",
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["wallet", "-created_at", "-id"],
                name="ledger_wallet_created_idx",
            ),
        ),
    ]
